name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    name: Deploy to Kubernetes (Test Environment)
    runs-on: ubuntu-latest
    needs: [test, sonarqube]  # Assurez-vous que les tests et l'analyse SonarQube réussissent avant le déploiement
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes CLI (kubectl)
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Authenticate with Kubernetes Cluster
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > $HOME/.kube/config

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: my-nestjs-app
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
          docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: kubectl rollout status deployment my-nestjs-app
